### ISSUE TITLE
Operands could not e broadcast together

### ISSUE THREAD

**Issue by orro3790** [PTRRupprecht/GenHurst#2]
ValueErrorTraceback (most recent call last)
<ipython-input-134-d3512c5f0f48> in <module>()
----> 1 genhurst(USDCAD_df['close_price'], 2)

<ipython-input-131-0d966f4fa393> in genhurst(S, q)
     22             SSxx = np.sum(X**2) - N*mx**2
     23             my = np.sum(Y)/N
---> 24             SSxy = np.sum( np.multiply(X,Y))  - N*mx*my
     25             cc1 = SSxy/SSxx
     26             cc2 = my - cc1*mx

ValueError: operands could not be broadcast together with shapes (1046,) (1045,)

**Comment by PTRRupprecht** [comment]
Hi orro3790,

I'm unable to reproduce your error.

Please have a look at your code, it seems to be changed compared to the original code (multipliers '*' and exponents '**' are missing at several locations, at least in the error message reported in your comment.

If I apply the original function on a random time series, no error is thrown. Please try this out:

trace = np.random.rand(1046,)
XX = genhurst(trace,2)

Please try this out as well, and if this does not solve the problem, also report the variable type and size of USDCAD_df['close_price'], as well as the Python version and operating system you're using.

**Comment by orro3790** [comment]
Working as intended now, thanks!

**Comment by PTRRupprecht** [comment]
Ok!

**Comment by kaustabhray** [comment]
I am getting the same error.

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[/tmp/ipykernel_64071/2180352199.py] in 
----> 1 gH = genhurst( data.Close, 2)
      2 
      3 print(gH)

[~/Projects/hurst-master/tests/genhurst.py] in genhurst(S, q)
     52             SSxx = np.sum(X**2) - N*mx**2
     53             my = np.sum(Y)[/](https://file+.vscode-resource.vscode-cdn.net/)N
---> 54             SSxy = np.sum( np.multiply(X,Y))  - N*mx*my
     55             cc1 = SSxy[/](https://file+.vscode-resource.vscode-cdn.net/)SSxx
     56             cc2 = my - cc1*mx

[~/anaconda3/lib/python3.9/site-packages/pandas/core/generic.py] in __array_ufunc__(self, ufunc, method, *inputs, **kwargs)
   2111         self, ufunc: np.ufunc, method: str, *inputs: Any, **kwargs: Any
   2112     ):
-> 2113         return arraylike.array_ufunc(self, ufunc, method, *inputs, **kwargs)
   2114 
   2115     # ----------------------------------------------------------------------

[~/anaconda3/lib/python3.9/site-packages/pandas/core/arraylike.py] in array_ufunc(self, ufunc, method, *inputs, **kwargs)
    263 
    264     # for binary ops, use our custom dunder methods
--> 265     result = maybe_dispatch_ufunc_to_dunder_op(self, ufunc, method, *inputs, **kwargs)
...
---> 19     return right * left
     20 
     21 

ValueError: operands could not be broadcast together with shapes (249,) (248,)
```
The screenshot is also attached.
file:///home/kray/Pictures/Screenshots/Screenshot%20from%202023-07-26%2022-29-35.png

**Comment by PTRRupprecht** [comment]
Hi,

You only added the local link to the screenshot, you did not really attach it.

From your code, I'm wondering:

- What does this expression in your code signify? `https://file+.vscode-resource.vscode-cdn.net/`
- Have you tried running the test code that I suggested in my reply from 30th of April 2019? If yes, does it run for you?
- What is the content of `data.Close`? Can you share the output of `data.Close.shape`?

Best,
Peter

**Comment by kaustabhray** [comment]
![Screenshot from 2023-07-26 22-29-35](https://github.com/PTRRupprecht/GenHurst/assets/140444615/70c221d2-f8b5-4225-82a2-368e24076e10)
Sorry. Attached the screenshot now.

1. Please disregard the that line, copy+paste problem. I use vscode for programming.
2. I have not yet tried running your test code, but i will do so now.
3. data.Close is a pandas series, shape (248,1)

regards.

**Comment by kaustabhray** [comment]
```python
trace = np.random.rand(248,)
XX = genhurst(trace,2)

print(XX)
```

The above test code works.

**Comment by kaustabhray** [comment]
Hi, I have got a workaround to use genhurst()
Convert pandas.series to ndarray before calling genhurst().
It seems genhurst works with numpy.ndarray.

see code below and attached screenshot.

```python
from genhurst import genhurst

# test the genhurst function
trace = np.random.rand(248,)
XX = genhurst(trace,2)

print(XX)

# convert pandas.series to numpy.ndarray
# this resolves the error
sdata = data.Close.to_numpy()


gH = genhurst( sdata, 2)


print(gH)
```

![Screenshot from 2023-07-27 00-00-58](https://github.com/PTRRupprecht/GenHurst/assets/140444615/c93b6a3a-e1b5-4ac9-8793-63ad82b97012)

**Comment by PTRRupprecht** [comment]
Thanks for coming back with your solution. I have now amended the information in the Readme that the input to the function should be a numpy array, as you have also found out.

Best wishes,
Peter

**Comment by kaustabhray** [comment]
Glad it was helpful, cheers.
Kaustabh Ray
KraySoft

Phone +91 9433278240
https://www.linkedin.com/in/kray42/
